import type { Resource } from '@/lib/types';

export const SESSION_LABEL: Record<NonNullable<Resource['session']>, string> = {
  feb_mar: 'February/March',
  may_jun: 'May/June',
  oct_nov: 'October/November',
  specimen: 'Specimen',
  practice: 'Practice',
};

export const TYPE_LABEL: Record<Resource['resource_type'], string> = {
  question_paper: 'Question paper',
  mark_scheme: 'Mark scheme',
  insert: 'Insert',
  specimen: 'Specimen paper',
  syllabus: 'Syllabus',
  practice_test: 'Practice test',
  examiner_report: 'Examiner report',
  notes: 'Notes',
  video: 'Video',
  other: 'Resource',
};

/** How a resource reached Chapter, in words a student understands. */
export function sourceBadge(r: Pick<Resource, 'source_type'>): { label: string; tone: 'neutral' | 'primary' | 'success' | 'info' } {
  switch (r.source_type) {
    case 'official_reference': return { label: 'Official source', tone: 'info' };
    case 'external_link': return { label: 'External link', tone: 'neutral' };
    case 'owned': return { label: 'Chapter-owned', tone: 'primary' };
    case 'licensed': return { label: 'Licensed', tone: 'success' };
    case 'open_license': return { label: 'Open licence', tone: 'success' };
    case 'generated': return { label: 'Generated by Chapter', tone: 'primary' };
  }
}

/** The action a resource offers: publishers' pages open on their own site. */
export function resourceAction(r: Pick<Resource, 'access' | 'source_type'>): string {
  if (r.access === 'download') return 'Download';
  if (r.access === 'hosted') return 'Open';
  return r.source_type === 'official_reference' ? 'Open official source' : 'Open link';
}

export function canLogScore(r: Pick<Resource, 'resource_type'>): boolean {
  return r.resource_type === 'question_paper' || r.resource_type === 'practice_test' || r.resource_type === 'specimen';
}
